### ISSUE TITLE
Memory management issue in relationals tests

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/OpenCL-CTS#1731] opened 2023-05-16 18:30 UTC
The following error is flagged from the floating point comparison tests (isequal, isgreater, isgreaterequal, isless, islessequal, islessgreater, isnotequal):
```
F0000 00:00:1684255904.098394    7568 debugallocation.cc:720] RAW: delete size mismatch: passed size 4 != requested / available size 24 / 24
    @     0x5573bae06f09  absl::raw_log_internal::RawLog()
    @     0x5573bae7f992  TCMallocInternalDeleteSized
    @     0x5573baca9e8c  MakeAndRunTest<>()
    @     0x5573bacc3e16  callSingleTestFunction()
    @     0x5573bacc3b07  callTestFunctions()
    @     0x5573bacc3564  parseAndCallCommandLineTests()
    @     0x5573bacc2e63  runTestHarnessWithCheck()
    @     0x5573bacc22b5  runTestHarness()
    @     0x7f3c93449633  __libc_start_main
    @     0x5573baca80ea  _start
```

**Comment by svenvh** [comment] 2023-05-23 13:48
@shajder could this be caused by #1623 which was merged last week?

**Comment by shajder** [comment] 2023-05-23 14:13
> @shajder could this be caused by #1623 which was merged last week?

that is an obvious suspect but I need way more info to investigate, this call stack is vague. @alan-baker could you deliver more info ? OS, compiler, architecture, complete log and other possible useful infos, thanks!

**Comment by alan-baker** [comment] 2023-05-23 15:19
#1739 does fix this issue.

**Closed** 2023-05-31 09:02 UTC
