### ISSUE TITLE
Wrong host_ptr set when creating images

### ISSUE THREAD

**Issue by aranpaop** [KhronosGroup/OpenCL-CTS#582] opened 2020-02-10 06:48 UTC
According to the OpenCL1.2 SPEC 5.3.1(either version 1.2 or 2.x has this distriction), the parameter **_host_ptr_** of **_clCreateImage_** must be **_null_** if the parameter **_flags_** is neither CL_USE_HOST_PTR nor CL_COPY_HOST_PTR:
> CL_INVALID_HOST_PTR if host_ptr is NULL and CL_MEM_USE_HOST_PTR or CL_MEM_COPY_HOST_PTR are set in flags or if host_ptr is not NULL but CL_MEM_COPY_HOST_PTR or CL_MEM_USE_HOST_PTR are not set in flags.

but here[[link](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/images/kernel_read_write/test_read_1D.cpp)] a not-null pointer **_imageValues_** has been transfered into **_create_image_1d_** and **_clCreateImage_**:
```
else // Either CL_MEM_ALLOC_HOST_PTR or none
    {
        // Note: if ALLOC_HOST_PTR is used, the driver allocates memory that can be accessed by the host, but otherwise
        // it works just as if no flag is specified, so we just do the same thing either way
        if(gTestMipmaps)
        {
            cl_image_desc image_desc = {0};
            image_desc.image_type = CL_MEM_OBJECT_IMAGE1D;
            image_desc.image_width = imageInfo->width;
            image_desc.num_mip_levels = imageInfo->num_mip_levels;

            unprotImage = clCreateImage( context,
                                        image_read_write_flags,
                                        imageInfo->format, &image_desc, NULL, &error);
            if( error != CL_SUCCESS )
            {
                log_error( "ERROR: Unable to create %d level mipmapped 1D image of size %d (pitch %d, %d ) (%s)",(int)imageInfo->num_mip_levels, (int)imageInfo->width, (int)imageInfo->rowPitch, (int)imageInfo->slicePitch, IGetErrorString( error ) );
                return error;
            }
        }
        else
        {
            unprotImage = create_image_1d( context,
                                          image_read_write_flags | gMemFlagsToUse,
                                          imageInfo->format,
                                          imageInfo->width, ( gEnablePitch ? imageInfo->rowPitch : 0 ),
                                          imageValues, NULL, &error );
            if( error != CL_SUCCESS )
            {
                log_error( "ERROR: Unable to create 1D image of size %d pitch %d (%s)\n", (int)imageInfo->width, (int)imageInfo->rowPitch, IGetErrorString( error ) );
                return error;
            }
        }
        image = unprotImage;
    }
```
Besides, if set **_nullptr_** instead of **_imageValue_**, it would also needs to transfer **_0_** as **_row_pitch_** and **_slice_pitch_** due to OpenCL1.2 SPEC 5.3.1.2:
> image_row_pitch is the scan-line pitch in bytes. This must be 0 if host_ptr is NULL and can
be either 0 or >= image_width * size of element in bytes if host_ptr is not NULL.

This happened in files below:
>test_conformance/images/kernel_read_write/test_iterations.cpp
test_conformance/images/kernel_read_write/test_read_1D.cpp
test_conformance/images/kernel_read_write/test_read_1D_array.cpp
test_conformance/images/kernel_read_write/test_read_2D_array.cpp
test_conformance/images/kernel_read_write/test_read_3D.cpp
test_conformance/images/kernel_read_write/test_write_1D.cpp
test_conformance/images/kernel_read_write/test_write_1D_array.cpp
test_conformance/images/kernel_read_write/test_write_2D_array.cpp
test_conformance/images/kernel_read_write/test_write_3D.cpp
test_conformance/images/kernel_read_write/test_write_image.cpp

Best regards!
Feb. 10. 2020

**Comment by kpet** [comment] 2021-01-19 09:08
Closing as a duplicate of #918 that links a proposed fix.

**Closed by kpet** 2021-01-19 09:08 UTC
Labels: bug
