### ISSUE TITLE
images/samplerlessReads/test_samplerless_reads CL_FLOAT fails where the float is subnormal

### ISSUE THREAD

**Issue by JasonTTang** [KhronosGroup/OpenCL-CTS#1023] opened 2020-10-21 20:56 UTC
For kernels such as:

__kernel void sample_kernel( read_only image1d_t input, sampler_t sampler, __global int *results )
{
   int tidX = get_global_id(0);
   int offset = tidX;
   float4 clr = read_imagef( input, tidX );
   int4 test = (clr != read_imagef( input, sampler, tidX ));
   if ( test.x || test.y || test.z || test.w )
      results[offset] = -1;
   else
      results[offset] = 0;
}

Exact equality should not be required for sampled and samplerless read when it comes to subnormals.

One option would be to avoid subnormal values in images (by replacing them with 0 or normal).  The other option would be for the kernel to replace any subnormal values with 0 before comparing.

**Comment by jlewis-austin** [comment] 2021-01-16 19:13
duplicates #512

**Comment by kpet** [comment] 2021-01-19 09:02
Closing as a duplicate of #512

**Closed by kpet** 2021-01-19 09:02 UTC
