### ISSUE TITLE
The lack of test cases with Half Precision Floating-Point in the master branch

### ISSUE THREAD

**Issue by luoanquan** [KhronosGroup/OpenCL-CTS#806] opened 2020-06-01 06:38 UTC
https://github.com/KhronosGroup/OpenCL-CTS/blob/58cf793fdb2d8786d772ab1fd7cedae6cf9cafdd/test_conformance/half/main.cpp#L56
![image](https://user-images.githubusercontent.com/29671255/83374819-4a7e4a80-a3ff-11ea-97fc-b14f103298ba.png)

As we can see in the master branch, only vload/vstore is tested in the “half” test group，without test cases for Half Precision Floating-Point in conversion/math/common/geometric/relational, etc.

The device info “CL_DEVICE_HALF_FP_CONFIG” is also not used in master branch for testing half denormal.

**Comment by jlewis-austin** [comment] 2021-01-16 18:52
This is a duplicate of #831

**Closed** 2021-09-27 20:31 UTC
