### ISSUE TITLE
Incorrect setting gDeviceType in images tests

### ISSUE THREAD

**Issue by gwawiork** [KhronosGroup/OpenCL-CTS#652] opened 2020-03-05 09:47 UTC
I noticed that some Images tests are failing after recent changes regarding moving gDeviceType variable to testHarness . Failures appears in case setting device type as test argument. Need to remove part of code from images tests which detects user params  with deviceType (and removes these parameters from the array) and allow testHarness.cpp do this. Current situation is that OpenCL-CTS\test_conformance\images\kernel_image_methods\main.cpp removes user param and testHarness overwirte user selection. The testHarness should be the only place where these parameters are discovered.

**Comment by kpet** [comment] 2020-03-05 10:03
Isn't that a duplicate of #574?

**Comment by gwawiork** [comment] 2020-03-05 10:30
Partially for sure

**Comment by gwawiork** [comment] 2020-03-05 10:35
Related with #611

**Closed** 2020-03-05 14:11 UTC
