### ISSUE TITLE
Wrong handling for denormals in half conformance host code

### ISSUE THREAD

**Issue by zakaria6868** [KhronosGroup/OpenCL-CTS#182] opened 2019-04-16 12:47 UTC
There's a bug in the host code of the conformance. Here's an explanation:
Host code running mode | Effect
ftz = 0 | (no errors)
ftz = 1 | for a = 0x33c00000 == 0x1.8p-24:device(a) = 0x0002float2half_rte(a) = 0x0000

The conformance reference code produces a wrong result in case the host code runs with ftz=1, for a (at least one) non-denormal input. The reference function float2half_rte in the file <conformace root>/Conformance_tests/test_conformance/half/Test_vStoreHalf.c is faulty and needs to be replaced.

**Comment by jlewis-austin** [comment] 2021-01-16 19:28
This can be closed. The reference function no longer exists in that file, and the denormal rounding/flushing issue is covered by #534 (and #540)

**Comment by kpet** [comment] 2021-01-19 09:05
Closing as a duplicate of #534 and #540.

**Closed by kpet** 2021-01-19 09:05 UTC
Labels: bug
