### ISSUE TITLE
The value returned for CL_DEVICE_OPENCL_C_VERSION isn't validated

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#364] opened 2019-07-08 09:40 UTC

**Comment by kpet** [comment] 2020-08-25 16:41
Likely to get done as part of #897

**Comment by neiltrevett** [comment] 2020-09-15 21:48
364 897 899 – should be looked at together

**Comment by bashbaug** [comment] 2020-09-21 16:58
Is this entirely a duplicate of #897 and #899 or is there something specific for it?

I'll note that the format of the string returned by `CL_DEVICE_OPENCL_C_VERSION` is validated by `test_api min_max_language_version`.  We do need to add tests to ensure the values returned are meaningful though, but I believe this is captured in #897 and #899.

If there is no specific action required for this issue then I think we should close it.

**Comment by bashbaug** [comment] 2020-09-21 23:02
Closing this issue.  If any additional checks are needed please include them in the review of PR #968.  Thanks!

**Closed by bashbaug** 2020-09-21 23:02 UTC
Labels: missing-coverage, must_fix_3.0
